In [1]:
import pandas as pd

In [5]:
quotes = pd.read_json('./quotes-2019-nytimes.json', orient='records', lines=True)

In [6]:
quotes.head()

,quoteID,quotation,speaker,qids,date,numOccurrences,probas,urls,phase
0,2019-04-17-024782,"It is not a low-income immigration,",James Fisher,"[Q16213953, Q20707104, Q43143598, Q58886302, Q...",2019-04-17 13:31:18,1,"[[James Fisher, 0.7475], [None, 0.2525]]",[https://www.nytimes.com/2019/04/17/realestate...,E
1,2019-04-02-001128,a champion figure skater switching to roller s...,John Updike,[Q105756],2019-04-02 14:58:33,2,"[[John Updike, 0.5856], [None, 0.4144]]",[https://www.nytimes.com/2019/04/02/opinion/vl...,E
2,2019-05-09-055187,It makes it much more difficult for him to mak...,None,[],2019-05-09 18:11:29,1,"[[None, 0.6493], [President Bill Clinton, 0.27...",[http://mobile.nytimes.com/2019/05/09/world/as...,E
3,2019-10-31-056366,"It puts me in a predicament,",Xavier Becerra,[Q1855840],2019-10-31 16:45:15,3,"[[Xavier Becerra, 0.9065], [None, 0.0909], [St...",[http://www.nytimes.com/2019/10/31/technology/...,E
4,2019-01-04-001792,A Pile of Leaves.,None,[],2019-01-04 10:00:07,1,"[[None, 0.8737], [Jason Fulford, 0.1263]]",[https://www.nytimes.com/2019/01/04/books/revi...,E

In [8]:
quotes.shape

(207527, 9)

In [11]:
quotes.describe()

       numOccurrences
count   207527.000000
mean         7.698844
std         55.648115
min          1.000000
25%          1.000000
50%          2.000000
75%          4.000000
max      12095.000000

In [13]:
quotes.sort_values(by='numOccurrences', ascending=False).head()

,quoteID,quotation,speaker,qids,date,numOccurrences,probas,urls,phase
21764,2019-04-12-080259,Star... [ + ] Wars: The Rise of Skywalker,None,[],2019-04-12 00:00:00,12095,"[[None, 0.4952], [J.J. Abrams, 0.0752], [Daisy...",[http://chronicle.northcoastnow.com/national-n...,E
19369,2019-09-20-084768,The president must be held accountable -- no o...,None,[],2019-09-20 00:00:00,4538,"[[None, 0.7259], [Nancy Pelosi, 0.1739], [Adam...",[http://www.canindia.com/trump-meets-zelensky-...,E
109000,2019-07-26-013259,Fight for Freedom. Stand with Hong Kong!!,Daryl Morey,[Q5226214],2019-07-26 17:32:18,3888,"[[Daryl Morey, 0.5921], [None, 0.2969], [LeBro...",[https://www.onenewspage.com/video/20190726/11...,E
182596,2019-03-01-125356,When They See Us.....,None,[],2019-03-01 15:21:56,3766,"[[None, 0.3952], [Ava DuVernay, 0.1959], [Jhar...",[https://www.thewrap.com/ava-duvernays-central...,E
197409,2019-01-29-100043,THIS IS MAGA COUNTRY!!!,Jussie Smollett,[Q6315685],2019-01-29 00:00:00,3519,"[[Jussie Smollett, 0.5677], [None, 0.3329], [P...",[http://news.lalate.com/2019/01/29/jussie-smol...,E